/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BuildingsRouteImport } from './routes/buildings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LeasesRouteImport } from './routes/leases'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as OwnersRouteImport } from './routes/owners'
import { Route as ParkingRouteImport } from './routes/parking'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as UtilitiesRouteImport } from './routes/utilities'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as VisitorsRouteImport } from './routes/visitors'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsRoute = BuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LeasesRoute = LeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersRoute = OwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingRoute = ParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesRoute = UtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorsRoute = VisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admin/admins',
  path: '/admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amenities': typeof AmenitiesRoute
  '/billing': typeof BillingRoute
  '/buildings': typeof BuildingsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leases': typeof LeasesRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/owners': typeof OwnersRoute
  '/parking': typeof ParkingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/tenants': typeof TenantsRoute
  '/units': typeof UnitsRoute
  '/utilities': typeof UtilitiesRoute
  '/verify-email': typeof VerifyEmailRoute
  '/visitors': typeof VisitorsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amenities': typeof AmenitiesRoute
  '/billing': typeof BillingRoute
  '/buildings': typeof BuildingsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leases': typeof LeasesRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/owners': typeof OwnersRoute
  '/parking': typeof ParkingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/tenants': typeof TenantsRoute
  '/units': typeof UnitsRoute
  '/utilities': typeof UtilitiesRoute
  '/verify-email': typeof VerifyEmailRoute
  '/visitors': typeof VisitorsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amenities': typeof AmenitiesRoute
  '/billing': typeof BillingRoute
  '/buildings': typeof BuildingsRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leases': typeof LeasesRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/owners': typeof OwnersRoute
  '/parking': typeof ParkingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/tenants': typeof TenantsRoute
  '/units': typeof UnitsRoute
  '/utilities': typeof UtilitiesRoute
  '/verify-email': typeof VerifyEmailRoute
  '/visitors': typeof VisitorsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amenities'
    | '/billing'
    | '/buildings'
    | '/dashboard'
    | '/forgot-password'
    | '/leases'
    | '/login'
    | '/maintenance'
    | '/owners'
    | '/parking'
    | '/profile'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/staff'
    | '/tenants'
    | '/units'
    | '/utilities'
    | '/verify-email'
    | '/visitors'
    | '/admin/admins'
    | '/admin/login'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amenities'
    | '/billing'
    | '/buildings'
    | '/dashboard'
    | '/forgot-password'
    | '/leases'
    | '/login'
    | '/maintenance'
    | '/owners'
    | '/parking'
    | '/profile'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/staff'
    | '/tenants'
    | '/units'
    | '/utilities'
    | '/verify-email'
    | '/visitors'
    | '/admin/admins'
    | '/admin/login'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/amenities'
    | '/billing'
    | '/buildings'
    | '/dashboard'
    | '/forgot-password'
    | '/leases'
    | '/login'
    | '/maintenance'
    | '/owners'
    | '/parking'
    | '/profile'
    | '/register'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/staff'
    | '/tenants'
    | '/units'
    | '/utilities'
    | '/verify-email'
    | '/visitors'
    | '/admin/admins'
    | '/admin/login'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmenitiesRoute: typeof AmenitiesRoute
  BillingRoute: typeof BillingRoute
  BuildingsRoute: typeof BuildingsRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LeasesRoute: typeof LeasesRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OwnersRoute: typeof OwnersRoute
  ParkingRoute: typeof ParkingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  TenantsRoute: typeof TenantsRoute
  UnitsRoute: typeof UnitsRoute
  UtilitiesRoute: typeof UtilitiesRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VisitorsRoute: typeof VisitorsRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings': {
      id: '/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof BuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leases': {
      id: '/leases'
      path: '/leases'
      fullPath: '/leases'
      preLoaderRoute: typeof LeasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners': {
      id: '/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof OwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parking': {
      id: '/parking'
      path: '/parking'
      fullPath: '/parking'
      preLoaderRoute: typeof ParkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities': {
      id: '/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof UtilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitors': {
      id: '/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof VisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmenitiesRoute: AmenitiesRoute,
  BillingRoute: BillingRoute,
  BuildingsRoute: BuildingsRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LeasesRoute: LeasesRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  OwnersRoute: OwnersRoute,
  ParkingRoute: ParkingRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  TenantsRoute: TenantsRoute,
  UnitsRoute: UnitsRoute,
  UtilitiesRoute: UtilitiesRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VisitorsRoute: VisitorsRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
