/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BuildingAccountsRouteImport } from './routes/building-accounts'
import { Route as BuildingsRouteImport } from './routes/buildings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmergencyContactsRouteImport } from './routes/emergency-contacts'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as FlatStatusRouteImport } from './routes/flat-status'
import { Route as FloorsRouteImport } from './routes/floors'
import { Route as LeasesRouteImport } from './routes/leases'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as OwnersRouteImport } from './routes/owners'
import { Route as ParkingRouteImport } from './routes/parking'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as PropertyRequestsRouteImport } from './routes/property-requests'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as UtilitiesRouteImport } from './routes/utilities'
import { Route as VisitorsRouteImport } from './routes/visitors'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as FloorsFloorIdUnitsRouteImport } from './routes/floors_.$floorId.units'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingAccountsRoute = BuildingAccountsRouteImport.update({
  id: '/building-accounts',
  path: '/building-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsRoute = BuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyContactsRoute = EmergencyContactsRouteImport.update({
  id: '/emergency-contacts',
  path: '/emergency-contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const FlatStatusRoute = FlatStatusRouteImport.update({
  id: '/flat-status',
  path: '/flat-status',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorsRoute = FloorsRouteImport.update({
  id: '/floors',
  path: '/floors',
  getParentRoute: () => rootRouteImport,
} as any)
const LeasesRoute = LeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersRoute = OwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingRoute = ParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyRequestsRoute = PropertyRequestsRouteImport.update({
  id: '/property-requests',
  path: '/property-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesRoute = UtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorsRoute = VisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admin/admins',
  path: '/admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorsFloorIdUnitsRoute = FloorsFloorIdUnitsRouteImport.update({
  id: '/floors_/$floorId/units',
  path: '/floors/$floorId/units',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amenities': typeof AmenitiesRoute
  '/billing': typeof BillingRoute
  '/building-accounts': typeof BuildingAccountsRoute
  '/buildings': typeof BuildingsRoute
  '/dashboard': typeof DashboardRoute
  '/emergency-contacts': typeof EmergencyContactsRoute
  '/expenses': typeof ExpensesRoute
  '/flat-status': typeof FlatStatusRoute
  '/floors': typeof FloorsRoute
  '/leases': typeof LeasesRoute
  '/maintenance': typeof MaintenanceRoute
  '/notices': typeof NoticesRoute
  '/owners': typeof OwnersRoute
  '/parking': typeof ParkingRoute
  '/properties': typeof PropertiesRoute
  '/property-requests': typeof PropertyRequestsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/tenants': typeof TenantsRoute
  '/units': typeof UnitsRoute
  '/utilities': typeof UtilitiesRoute
  '/visitors': typeof VisitorsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/floors/$floorId/units': typeof FloorsFloorIdUnitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amenities': typeof AmenitiesRoute
  '/billing': typeof BillingRoute
  '/building-accounts': typeof BuildingAccountsRoute
  '/buildings': typeof BuildingsRoute
  '/dashboard': typeof DashboardRoute
  '/emergency-contacts': typeof EmergencyContactsRoute
  '/expenses': typeof ExpensesRoute
  '/flat-status': typeof FlatStatusRoute
  '/floors': typeof FloorsRoute
  '/leases': typeof LeasesRoute
  '/maintenance': typeof MaintenanceRoute
  '/notices': typeof NoticesRoute
  '/owners': typeof OwnersRoute
  '/parking': typeof ParkingRoute
  '/properties': typeof PropertiesRoute
  '/property-requests': typeof PropertyRequestsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/tenants': typeof TenantsRoute
  '/units': typeof UnitsRoute
  '/utilities': typeof UtilitiesRoute
  '/visitors': typeof VisitorsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/floors/$floorId/units': typeof FloorsFloorIdUnitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amenities': typeof AmenitiesRoute
  '/billing': typeof BillingRoute
  '/building-accounts': typeof BuildingAccountsRoute
  '/buildings': typeof BuildingsRoute
  '/dashboard': typeof DashboardRoute
  '/emergency-contacts': typeof EmergencyContactsRoute
  '/expenses': typeof ExpensesRoute
  '/flat-status': typeof FlatStatusRoute
  '/floors': typeof FloorsRoute
  '/leases': typeof LeasesRoute
  '/maintenance': typeof MaintenanceRoute
  '/notices': typeof NoticesRoute
  '/owners': typeof OwnersRoute
  '/parking': typeof ParkingRoute
  '/properties': typeof PropertiesRoute
  '/property-requests': typeof PropertyRequestsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/tenants': typeof TenantsRoute
  '/units': typeof UnitsRoute
  '/utilities': typeof UtilitiesRoute
  '/visitors': typeof VisitorsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/floors_/$floorId/units': typeof FloorsFloorIdUnitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amenities'
    | '/billing'
    | '/building-accounts'
    | '/buildings'
    | '/dashboard'
    | '/emergency-contacts'
    | '/expenses'
    | '/flat-status'
    | '/floors'
    | '/leases'
    | '/maintenance'
    | '/notices'
    | '/owners'
    | '/parking'
    | '/properties'
    | '/property-requests'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/subscriptions'
    | '/tenants'
    | '/units'
    | '/utilities'
    | '/visitors'
    | '/admin/admins'
    | '/admin/login'
    | '/admin/'
    | '/floors/$floorId/units'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amenities'
    | '/billing'
    | '/building-accounts'
    | '/buildings'
    | '/dashboard'
    | '/emergency-contacts'
    | '/expenses'
    | '/flat-status'
    | '/floors'
    | '/leases'
    | '/maintenance'
    | '/notices'
    | '/owners'
    | '/parking'
    | '/properties'
    | '/property-requests'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/subscriptions'
    | '/tenants'
    | '/units'
    | '/utilities'
    | '/visitors'
    | '/admin/admins'
    | '/admin/login'
    | '/admin'
    | '/floors/$floorId/units'
  id:
    | '__root__'
    | '/'
    | '/amenities'
    | '/billing'
    | '/building-accounts'
    | '/buildings'
    | '/dashboard'
    | '/emergency-contacts'
    | '/expenses'
    | '/flat-status'
    | '/floors'
    | '/leases'
    | '/maintenance'
    | '/notices'
    | '/owners'
    | '/parking'
    | '/properties'
    | '/property-requests'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/subscriptions'
    | '/tenants'
    | '/units'
    | '/utilities'
    | '/visitors'
    | '/admin/admins'
    | '/admin/login'
    | '/admin/'
    | '/floors_/$floorId/units'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmenitiesRoute: typeof AmenitiesRoute
  BillingRoute: typeof BillingRoute
  BuildingAccountsRoute: typeof BuildingAccountsRoute
  BuildingsRoute: typeof BuildingsRoute
  DashboardRoute: typeof DashboardRoute
  EmergencyContactsRoute: typeof EmergencyContactsRoute
  ExpensesRoute: typeof ExpensesRoute
  FlatStatusRoute: typeof FlatStatusRoute
  FloorsRoute: typeof FloorsRoute
  LeasesRoute: typeof LeasesRoute
  MaintenanceRoute: typeof MaintenanceRoute
  NoticesRoute: typeof NoticesRoute
  OwnersRoute: typeof OwnersRoute
  ParkingRoute: typeof ParkingRoute
  PropertiesRoute: typeof PropertiesRoute
  PropertyRequestsRoute: typeof PropertyRequestsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TenantsRoute: typeof TenantsRoute
  UnitsRoute: typeof UnitsRoute
  UtilitiesRoute: typeof UtilitiesRoute
  VisitorsRoute: typeof VisitorsRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  FloorsFloorIdUnitsRoute: typeof FloorsFloorIdUnitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building-accounts': {
      id: '/building-accounts'
      path: '/building-accounts'
      fullPath: '/building-accounts'
      preLoaderRoute: typeof BuildingAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings': {
      id: '/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof BuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-contacts': {
      id: '/emergency-contacts'
      path: '/emergency-contacts'
      fullPath: '/emergency-contacts'
      preLoaderRoute: typeof EmergencyContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flat-status': {
      id: '/flat-status'
      path: '/flat-status'
      fullPath: '/flat-status'
      preLoaderRoute: typeof FlatStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floors': {
      id: '/floors'
      path: '/floors'
      fullPath: '/floors'
      preLoaderRoute: typeof FloorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leases': {
      id: '/leases'
      path: '/leases'
      fullPath: '/leases'
      preLoaderRoute: typeof LeasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners': {
      id: '/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof OwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parking': {
      id: '/parking'
      path: '/parking'
      fullPath: '/parking'
      preLoaderRoute: typeof ParkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-requests': {
      id: '/property-requests'
      path: '/property-requests'
      fullPath: '/property-requests'
      preLoaderRoute: typeof PropertyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities': {
      id: '/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof UtilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitors': {
      id: '/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof VisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floors_/$floorId/units': {
      id: '/floors_/$floorId/units'
      path: '/floors/$floorId/units'
      fullPath: '/floors/$floorId/units'
      preLoaderRoute: typeof FloorsFloorIdUnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmenitiesRoute: AmenitiesRoute,
  BillingRoute: BillingRoute,
  BuildingAccountsRoute: BuildingAccountsRoute,
  BuildingsRoute: BuildingsRoute,
  DashboardRoute: DashboardRoute,
  EmergencyContactsRoute: EmergencyContactsRoute,
  ExpensesRoute: ExpensesRoute,
  FlatStatusRoute: FlatStatusRoute,
  FloorsRoute: FloorsRoute,
  LeasesRoute: LeasesRoute,
  MaintenanceRoute: MaintenanceRoute,
  NoticesRoute: NoticesRoute,
  OwnersRoute: OwnersRoute,
  ParkingRoute: ParkingRoute,
  PropertiesRoute: PropertiesRoute,
  PropertyRequestsRoute: PropertyRequestsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TenantsRoute: TenantsRoute,
  UnitsRoute: UnitsRoute,
  UtilitiesRoute: UtilitiesRoute,
  VisitorsRoute: VisitorsRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  FloorsFloorIdUnitsRoute: FloorsFloorIdUnitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
